title: "Noah Scott CV"
show_downloads: false
theme: jekyll-theme-cayman
sass:
  style: compressed
github:
  is_project_page: false
include:
  - assets/css

# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme
